name: addx_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  get: ^4.6.5
  dio: ^4.0.6
  get_it: ^7.2.0
  fluttertoast: ^8.1.3
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  build_runner: ^2.3.2
  test: ^1.21.6
flutter:
  uses-material-design: true
